#!/bin/bash

COMMAND=$1

if [[ -z $COMMAND ]]; then
   echo "Available commands are:"
   echo "  start          - start hmpg server"
   echo "  stop           - stop hmpg server (currently the same as kill)"
   echo "  status         - status of hmpg server"
   echo "  kill           - kill hmpg processes"
   echo "  restart        - restart hmpg server"
   
   echo "  logs           - application logs"
   echo "  pm2_logs       - pm2 hmpg logs"
   echo "  pm2_error_logs - pm2 hmpg error logs"

   echo "  run_front_end  - runs local front end on 8080"
fi


if [[ $COMMAND == "start" ]]; then
    cd /var/www/homepage/homepage-backend && pm2 start homepage.sh && cd -
fi

if [[ $COMMAND == "stop" ]]; then
    pm2 stop homepage
    # ps -ea | grep node | awk "{print \$1}" | xargs sudo kill
fi

if [[ $COMMAND == "status" ]]; then
    pm2 status homepage
fi

if [[ $COMMAND == "kill" ]]; then
    ps -ea | grep node | awk "{print \$1}" | xargs sudo kill
fi

if [[ $COMMAND == "restart" ]]; then
    pm2 restart homepage
    # ps -ea | grep node | awk "{print \$1}" | xargs sudo kill
    # cd /var/www/homepage/homepage-backend && pm2 start homepage.sh && cd -
fi

if [[ $COMMAND == "logs" ]]; then
    cd /var/www/homepage/logs/ && date +%Y-%m-%d | xargs cat && cd -
fi

if [[ $COMMAND == "pm2_logs" ]]; then
    cat ~/.pm2/logs/homepage-out.log
fi

if [[ $COMMAND == "pm2_error_logs" ]]; then
    cat ~/.pm2/logs/homepage-error.log
fi

if [[ $COMMAND == "run_front_end" ]]; then
    cd /var/www/homepage/homepage && ng serve --proxy-config proxy.config.json && cd -
fi
