#!/bin/bash

COMMAND=$1

if [[ -z $COMMAND ]]; then
   echo "Available commands are:"
   echo "  start          - start hmpg server"
   echo "  stop           - stop hmpg server"
   echo "  status         - status of hmpg server"
   echo "  kill           - kill hmpg processes"
   echo "  resurrect      - restart hmpg server"
   
   echo "  fetch          - update notice feed data"
   echo "  deploy         - deploy code changes to prod"
   echo "  logs           - application logs"
   echo "  pm2_logs       - pm2 hmpg logs"
   echo "  pm2_error_logs - pm2 hmpg error logs"

   echo "  run_fe         - runs local front end on 8080"
fi


if [[ $COMMAND == "start" ]]; then
    cd /var/www/homepage/homepage-backend && pm2 start homepage.sh && cd -
fi

if [[ $COMMAND == "stop" ]]; then
    pm2 stop homepage
fi

if [[ $COMMAND == "status" ]]; then
    pm2 status homepage
fi

if [[ $COMMAND == "kill" ]]; then
    pm2 del homepage
    ps -ea | grep node | awk "{print \$1}" | xargs sudo kill
fi

if [[ $COMMAND == "resurrect" ]]; then
    pm2 resurrect
fi

if [[ $COMMAND == "fetch" ]]; then
    cd /var/www/homepage/ && python3 notice_feed.py && cd -
fi

if [[ $COMMAND == "deploy" ]]; then
    cd /var/www/homepage/homepage && ng build
    cd /var/www/homepage/homepage-backend && npm run build
fi

if [[ $COMMAND == "logs" ]]; then
    cd /var/www/homepage/logs/ && date +%Y-%m-%d | xargs cat && cd -
fi

if [[ $COMMAND == "pm2_logs" ]]; then
    cat ~/.pm2/logs/homepage-out.log
fi

if [[ $COMMAND == "pm2_error_logs" ]]; then
    cat ~/.pm2/logs/homepage-error.log
fi

if [[ $COMMAND == "run_fe" ]]; then
    cd /var/www/homepage/homepage && ng serve --proxy-config proxy.config.json && cd -
fi
